[icons.nnn]
# nerdfont = "ó°¡˜"
# color = "blue"
emoji = "ğŸ“‚"

[icons.neomutt]
# nerdfont = "ó°¡˜"
# color = "blue"
# emoji = "ğŸ“«"
emoji = "âœ‰ï¸ "

[icons.nvim]
emoji = "îŸ…"

[default]
# nerdfont = "î¯Š"
# color = "red"
emoji = "âš¡"
